require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SConcernsController do

  # This should return the minimal set of attributes required to create a valid
  # SConcern. As you add validations to SConcern, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SConcernsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all s_concerns as @s_concerns" do
      s_concern = SConcern.create! valid_attributes
      get :index, {}, valid_session
      assigns(:s_concerns).should eq([s_concern])
    end
  end

  describe "GET show" do
    it "assigns the requested s_concern as @s_concern" do
      s_concern = SConcern.create! valid_attributes
      get :show, {:id => s_concern.to_param}, valid_session
      assigns(:s_concern).should eq(s_concern)
    end
  end

  describe "GET new" do
    it "assigns a new s_concern as @s_concern" do
      get :new, {}, valid_session
      assigns(:s_concern).should be_a_new(SConcern)
    end
  end

  describe "GET edit" do
    it "assigns the requested s_concern as @s_concern" do
      s_concern = SConcern.create! valid_attributes
      get :edit, {:id => s_concern.to_param}, valid_session
      assigns(:s_concern).should eq(s_concern)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SConcern" do
        expect {
          post :create, {:s_concern => valid_attributes}, valid_session
        }.to change(SConcern, :count).by(1)
      end

      it "assigns a newly created s_concern as @s_concern" do
        post :create, {:s_concern => valid_attributes}, valid_session
        assigns(:s_concern).should be_a(SConcern)
        assigns(:s_concern).should be_persisted
      end

      it "redirects to the created s_concern" do
        post :create, {:s_concern => valid_attributes}, valid_session
        response.should redirect_to(SConcern.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved s_concern as @s_concern" do
        # Trigger the behavior that occurs when invalid params are submitted
        SConcern.any_instance.stub(:save).and_return(false)
        post :create, {:s_concern => {}}, valid_session
        assigns(:s_concern).should be_a_new(SConcern)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SConcern.any_instance.stub(:save).and_return(false)
        post :create, {:s_concern => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested s_concern" do
        s_concern = SConcern.create! valid_attributes
        # Assuming there are no other s_concerns in the database, this
        # specifies that the SConcern created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SConcern.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => s_concern.to_param, :s_concern => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested s_concern as @s_concern" do
        s_concern = SConcern.create! valid_attributes
        put :update, {:id => s_concern.to_param, :s_concern => valid_attributes}, valid_session
        assigns(:s_concern).should eq(s_concern)
      end

      it "redirects to the s_concern" do
        s_concern = SConcern.create! valid_attributes
        put :update, {:id => s_concern.to_param, :s_concern => valid_attributes}, valid_session
        response.should redirect_to(s_concern)
      end
    end

    describe "with invalid params" do
      it "assigns the s_concern as @s_concern" do
        s_concern = SConcern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SConcern.any_instance.stub(:save).and_return(false)
        put :update, {:id => s_concern.to_param, :s_concern => {}}, valid_session
        assigns(:s_concern).should eq(s_concern)
      end

      it "re-renders the 'edit' template" do
        s_concern = SConcern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SConcern.any_instance.stub(:save).and_return(false)
        put :update, {:id => s_concern.to_param, :s_concern => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested s_concern" do
      s_concern = SConcern.create! valid_attributes
      expect {
        delete :destroy, {:id => s_concern.to_param}, valid_session
      }.to change(SConcern, :count).by(-1)
    end

    it "redirects to the s_concerns list" do
      s_concern = SConcern.create! valid_attributes
      delete :destroy, {:id => s_concern.to_param}, valid_session
      response.should redirect_to(s_concerns_url)
    end
  end

end
